services:
  db:
    image: postgres:15
    container_name: mikopbx_db
    environment:
      - POSTGRES_USER=${DB_USER:-mikouser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-mikopass}
      - POSTGRES_DB=${DB_NAME:-mikodb}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  mikopbx:
    image: mikopbx/mikopbx:latest
    container_name: mikopbx_app
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-8080}:80"
      - "${SIP_PORT:-5060}:${SIP_PORT:-5060}/udp"
      - "${SIP_PORT:-5060}:${SIP_PORT:-5060}/tcp"
      - "${RTP_START:-10000}-${RTP_END:-20000}:${RTP_START:-10000}-${RTP_END:-20000}/udp"
    environment:
      - TZ=${TZ:-Asia/Karachi}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-mikouser}
      - DB_PASSWORD=${DB_PASSWORD:-mikopass}
      - DB_NAME=${DB_NAME:-mikodb}
    volumes:
      - /var/spool/mikopbx/cf:/var/spool/mikopbx/cf
      - /var/spool/mikopbx/storage:/var/spool/mikopbx/storage
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  db-data:
