version: "3.8"

services:
  mikopbx:
    container_name: "mikopbx"
    image: "ghcr.io/mikopbx/mikopbx-x86-64"
    entrypoint: "/sbin/docker-entrypoint"
    hostname: "mikopbx-in-docker"
    volumes:
      - ./cf:/cf
      - ./storage:/storage
    tty: true
    cap_add:
      - NET_ADMIN
    environment:
      - ID_WWW_USER=${ID_WWW_USER}
      - ID_WWW_GROUP=${ID_WWW_GROUP}
      - PBX_NAME=${PBX_NAME}
      - RTP_PORT_FROM=${RTP_PORT_FROM}
      - RTP_PORT_TO=${RTP_PORT_TO}
      - WEB_ADMIN_LOGIN=${WEB_ADMIN_LOGIN}
      - WEB_ADMIN_PASSWORD=${WEB_ADMIN_PASSWORD}
      - ENABLE_USE_NAT=${ENABLE_USE_NAT}
      - PBX_FIREWALL_ENABLED=${PBX_FIREWALL_ENABLED}
      - PBX_FAIL2BAN_ENABLED=${PBX_FAIL2BAN_ENABLED}
      - EXTERNAL_SIP_PORT=${EXTERNAL_SIP_PORT}
    ports:
      - "${WEB_HTTPS_PORT}:443"
      - "${SIP_PORT}:5060/udp"

networks:
  default:
    driver: bridge
