version: "3.8"

services:
  db:
    image: ${DB_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  mikopbx:
    image: ${MIKO_IMAGE}
    container_name: zabbix/zabbix-server-pgsql:latest
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:80"
      - "${SIP_PORT}:${SIP_PORT}/udp"
      - "${SIP_PORT}:${SIP_PORT}/tcp"
      - "${RTP_START}-${RTP_END}:${RTP_START}-${RTP_END}/udp"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - /var/spool/mikopbx/cf:/var/spool/mikopbx/cf
      - /var/spool/mikopbx/storage:/var/spool/mikopbx/storage
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  db-data:
