version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: zabbix_jenkins
    privileged: true
    user: root          # ✅ important: run as root inside container
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins
    restart: always

volumes:
  jenkins_home:
