version: "3.8"

services:
  mikopbx-first:
    container_name: "mikopbx-first"
    image: "ghcr.io/mikopbx/mikopbx-x86-64"
    entrypoint: "/sbin/docker-entrypoint"
    hostname: "mikopbx-in-docker-first"
    volumes:
      - ./first/cf:/cf
      - ./first/storage:/storage
    tty: true
    cap_add:
      - NET_ADMIN
    environment:
      - ID_WWW_USER=${ID_WWW_USER}
      - ID_WWW_GROUP=${ID_WWW_GROUP}
      - PBX_NAME=${PBX_NAME_FIRST}
      - RTP_PORT_FROM=${RTP_PORT_FROM_FIRST}
      - RTP_PORT_TO=${RTP_PORT_TO_FIRST}
      - WEB_ADMIN_LOGIN=${WEB_ADMIN_LOGIN_FIRST}
      - WEB_ADMIN_PASSWORD=${WEB_ADMIN_PASSWORD_FIRST}
      - ENABLE_USE_NAT=${ENABLE_USE_NAT_FIRST}
      - PBX_FIREWALL_ENABLED=${PBX_FIREWALL_ENABLED_FIRST}
      - PBX_FAIL2BAN_ENABLED=${PBX_FAIL2BAN_ENABLED_FIRST}
    ports:
      - "${WEB_HTTPS_PORT_FIRST}:443"
      - "${SIP_PORT_FIRST}:5060/udp"

  mikopbx-second:
    container_name: "mikopbx-second"
    image: "ghcr.io/mikopbx/mikopbx-x86-64"
    entrypoint: "/sbin/docker-entrypoint"
    hostname: "mikopbx-in-docker-second"
    volumes:
      - ./second/cf:/cf
      - ./second/storage:/storage
    tty: true
    cap_add:
      - NET_ADMIN
    environment:
      - ID_WWW_USER=${ID_WWW_USER}
      - ID_WWW_GROUP=${ID_WWW_GROUP}
      - PBX_NAME=${PBX_NAME_SECOND}
      - RTP_PORT_FROM=${RTP_PORT_FROM_SECOND}
      - RTP_PORT_TO=${RTP_PORT_TO_SECOND}
      - WEB_ADMIN_LOGIN=${WEB_ADMIN_LOGIN_SECOND}
      - WEB_ADMIN_PASSWORD=${WEB_ADMIN_PASSWORD_SECOND}
      - ENABLE_USE_NAT=${ENABLE_USE_NAT_SECOND}
      - PBX_FIREWALL_ENABLED=${PBX_FIREWALL_ENABLED_SECOND}
      - PBX_FAIL2BAN_ENABLED=${PBX_FAIL2BAN_ENABLED_SECOND}
      - EXTERNAL_SIP_PORT=${EXTERNAL_SIP_PORT_SECOND}
    ports:
      - "${WEB_HTTPS_PORT_SECOND}:443"
      - "${SIP_PORT_SECOND}:5060/udp"

networks:
  default:
    driver: bridge
